### ISSUE TITLE
Use types

### ISSUE THREAD

**Issue by DavidNemeskey** [Hollo1996/SlimeAnUTLE#1]
@Hollo1996 I've been thinking about how ugly it is that you have to write stuff like this in the Parser grammar:

```
slot: slotHead spslBody slotTail;
slotHead: (BOB_SLOT|OLB_SLOT|COB_SLOT|
            BOB_SLOT_B_O|OLB_SLOT_B_O|COB_SLOT_B_O|
            BOB_SLOT_O_O|OLB_SLOT_O_O|COB_SLOT_O_O|
            BOB_SLOT_C_O|OLB_SLOT_C_O|COB_SLOT_C_O|
            BOB_SLOT_B_T|OLB_SLOT_B_T|COB_SLOT_B_T|
            BOB_SLOT_O_T|OLB_SLOT_O_T|COB_SLOT_O_T|
            BOB_SLOT_C_T|OLB_SLOT_C_T|COB_SLOT_C_T);
slotTail:(BCB_SLOT|NL_SLSP|NW_SLSP);
```

And you know what? You don't. :smile: I've just found this: https://stackoverflow.com/questions/15807322/how-to-define-tokens-that-can-appear-in-multiple-lexical-modes-in-antlr4

What it says, basically, is that you can use `type()` to tell the Lexer to emit a different token than the one it encountered. So you can get rid of all those `BOB_SLOT_*_*` tokens, like so:

```
# Lexer

BOB_SLOT : '{$'     -> pushMode(B_SLSP);
...
# In mode B_OPER
BOB_SLOT_B_O : '{$'    -> type(BOB_SLOT), pushMode(B_SLSP);
...
# In mode O_OPER
BOB_SLOT_O_O : '{$'    -> type(BOB_SLOT), pushMode(B_SLSP);
...
# etc.

# Parser
slotHead: (BOB_SLOT|OLD_SLOT|COB_SLOT);
```

Much nicer, isn't it? :triumph:

**Comment by Hollo1996** [comment]
Woow. Nice. I reduced code wit it where ever I could. :)
